### ISSUE TITLE
Improve testability of ContextHub?

### ISSUE THREAD

**Issue by sb89** [LiamKenneth/ArchaicQuest#66]
Is it worth attempting to improve the testability of `ContextHub`?

I was thinking about writing some tests for `WakePlayer()` but I realised there isn't a straightforward way of mocking/stubbing the `HubContext.SendToClient` call.

**Comment by LiamKenneth** [comment]
Yeah,  i never really knew where to being with stubbing Hubcontext. I have really limited knowledge on testing. 

The tests i have written are because they don't call hubcontext so are quite simple to do. 

Do you have any ideas? I'm totally for writing tests for all the commands. It makes sense.
